version: "3"
services:
  redis:
    image: redis:latest
    container_name: gitlab-redis
    restart: always
    command: --loglevel warning
    volumes:
    - /srv/storage/redis/data:/var/lib/redis

  postgresql:
    image: postgres:9.6.5
    container_name: gitlab-postgres
    restart: always
    environment:
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=pass
    - POSTGRES_DB=gitlabhq_production
    - PG_DATA=/var/lib/postgresql/data/
    volumes:
    - /srv/storage/postgresql:/var/lib/postgresql/data/

  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.example.dev'
        
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        gitlab_rails['redis_host'] = "redis"
        gitlab_rails['redis_port'] = 6379
        redis['enable'] = "false"
        
        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_database'] = "gitlabhq_production"
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_port'] = 5432
        postgresql['enable'] = "false"
    volumes:
      - /srv/storage/gitlab/config:/etc/gitlab
      - /srv/certs:/certs
      - /srv/storage/gitlab/logs:/var/log/gitlab
      - /srv/storage/gitlab/data:/var/opt/gitlab
    ports:
      - "80:80"
      - "10022:22"

  gitlab-runner-1:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner-1
    restart: always
    depends_on:
      - gitlab
    environment:
      - CI_SERVER_URL=http://gitlab/ci
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/storage/gitlab-runner/config-1:/etc/gitlab-runner
      - /srv/storage/gitlab-runner/data:/home/gitlab_ci_multi_runner/data
  gitlab-runner-2:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner-2
    restart: always
    depends_on:
      - gitlab
    environment:
      - CI_SERVER_URL=http://gitlab/ci
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/storage/gitlab-runner/config-2:/etc/gitlab-runner
      - /srv/storage/gitlab-runner/data:/home/gitlab_ci_multi_runner/data

  registry:
    image: registry:2
    container_name: registry
    restart: always
    volumes:
      - /srv/auth:/auth
      - /srv/certs:/certs
      - /srv/storage/registry/config:/etc/docker/registry
      - /srv/storage/registry:/var/lib/registry
    ports:
      - "5000:5000"
