concurrent = 1
check_interval = 0

[[runners]]
  name = "Docker"
  url = "http://gitlab/ci"
  token = "custom1token"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "python:latest"
    privileged = true
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/srv/ssh:/ssh", "/cache"]
    extra_hosts = ["git.example.dev:192.168.1.2"]
    shm_size = 0
  [runners.cache]
